### ISSUE TITLE
Database status

### ISSUE THREAD

**Issue by hubertsvk** [JPangburn314/Zabbix3.4-MSSQL-2008-2016#10]
on Server 2012 r2 and SQL 2014 SP3 all working fine

on Server 2012 r2 and SQL 2012 SP4 database status showing "Not Supported Value "Error executing query on !" of type "string" is not suitable for value type "Numeric (unsigned)"

Zabbix server 4.4.5
Zabbix agent 4.4.6

**Comment by adoang1919** [comment]
Hi, is it working on zabbix 5 ?
